HW8 completed
DonArtEllo/Navigation_-VContakte- pull request #8
Opened 2021-11-24 21:01 UTC by DonArtEllo

Completed all parts of HomeWork "Asynchronous development. Multithreading"

2021-12-19 18:24 UTC, denisnzrk requested changes

2021-12-19 18:24 UTC, denisnzrk commented on Navigation/NFTCollectionModule/NFTCollectionViewController.swift
> +        processorOnThread.processImagesOnThread(sourceImages: viewModel.nftImages, filter: .colorInvert, qos: .userInteractive) { (processedImages) in
Вызывать процессинг в ячейке в данном случае неправильно.
Необходимо вызвать его один раз где-нибудь во viewDidLoad :)
Тут вы запускаете слишком много операций для групп картинок при реюзе ячеек.

2021-12-21 11:33 UTC, DonArtEllo commented on Navigation/NFTCollectionModule/NFTCollectionViewController.swift
> +        processorOnThread.processImagesOnThread(sourceImages: viewModel.nftImages, filter: .colorInvert, qos: .userInteractive) { (processedImages) in
Внёс исправления: 

1. Перенёс процессинг в отдельную функцию
2. Вызов функции происходит во viewDidLoad
3. Сделал перерасчет времени (пункт 6 задания)

```
private func processImages() {
        NSLog ("Start")
        processorOnThread.processImagesOnThread(sourceImages: viewModel.nftImages, filter: .monochrome(color: .red, intensity: 2), qos: .background)
            { (resultImages) in
                DispatchQueue.main.async {
                    for image in resultImages {
                        self.processedImages.append(image!)
                    }
                    self.collectionView.reloadData()
                    NSLog ("Ended")
                }
            }
    }
```

2021-12-21 11:44 UTC, DonArtEllo commented
Need to be reworked

2021-12-21 11:44 UTC, closed without merging